<form action="<?php echo $block->getGateUrl(); ?>" method="POST" id="FONDY_payment_form" style="display: none">
    <?php foreach ($block->getPostData() as $name => $value): ?>
        <input type="hidden" name="<?php echo $block->escapeHtml($name); ?>"
               value="<?php echo $block->escapeHtml($value); ?>"/>
    <?php endforeach; ?>
</form>
<button class="action primary" type="submit" form="FONDY_payment_form">Submit</button>
<script type="text/javascript">
     window.onload = function() {
        document.getElementById("FONDY_payment_form").submit();
     }
</script>
