<form action="<?php echo $block->getGateUrl(); ?>" method="POST" id="FONDY_payment_form" style="display: none">
    <?php if (!is_null($block->getPostData())): ?>
        <?php foreach ($block->getPostData() as $name => $value): ?>
            <input type="hidden" name="<?php echo $block->escapeHtml($name); ?>"
                   value="<?php echo $block->escapeHtml($value); ?>"/>
        <?php endforeach; ?>
    <?php endif; ?>
</form>
<button class="action primary" type="submit" form="FONDY_payment_form">Submit</button>
<script type="text/javascript">
    require(["jquery"], function ($) {
        $(document).ready(function () {
            //$('#FONDY_payment_form').submit();
        });
    });
</script>
